/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.google.gson.Gson;

public class App {

    public static void main(String[] args) {
        User user = new User("Olya","Gorgula");
        System.out.println(new Gson().toJson(user));
    }
}
